<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<artifactId>mass-core</artifactId>
	<packaging>jar</packaging>

	<parent>
		<groupId>edu.uw.bothell.css.mass</groupId>
		<artifactId>MASS-Java</artifactId>
		<version>0.8.2-SNAPSHOT</version>
	</parent>

	<name>MASS Java Core Library</name>

	<dependencies>
		<dependency>
			<!-- For SSH connectivity to remote hosts -->
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
			<version>0.1.51</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<!--  For JAXB serialization to/from XML -->
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-core</artifactId>
			<version>2.2.11</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<finalName>MASS</finalName>
        			<appendAssemblyId>false</appendAssemblyId>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
